accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

gen/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView
from . import views
app_name = "gen"
urlpatterns = [
    path("", views.home, name="home"),
    path("input/", views.input, name="input"), # get user input
    path("story/", views.story, name="story"), # for viewing stories
    path("segments/", views.segments, name="segments"), # for viewing story segments
    path("images/", views.images, name="images"), # for viewing story images
    path("webtoon/", views.webtoon, name="webtoon"), # for viewing final webtoon
]

webtoon/urls.py
from django.views.generic.base import TemplateView

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("gen/", include("gen.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("accounts/", include("django.contrib.auth.urls"))
    
]

accounts/models.py
from django.db import models

# Create your models here.

gen/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User

class Story(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=20, default=user.name)
    text = models.CharField(max_length = 800)
    num_chapters = models.IntegerField(default=4)
    pub_date =  models.DateTimeField(default=timezone.now)
    font = None

    def __str__(self):
        return self.title
    

class Character(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    details = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name
    
# will be updated by user choices
class Context(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    location = models.CharField(max_length=20)
    details = models.CharField(max_length=200)
    pub_date =  models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.location


class Chapter(models.Model):
    story = models.ForeignKey(Story, on_delete=models.CASCADE)
    mood = models.CharField(max_length=200)
    chapter_name = models.CharField(max_length=200)
    chapter_num = models.IntegerField(default=1)
    pub_date =  models.DateTimeField(default=timezone.now)
    filter = None
    def __str__(self):
        return f"Chapter {self.chapter_num}: {self.chapter_name}"
    

class Panel(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    mood = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    image_url = models.CharField(max_length=200)
    dialogue = models.CharField(max_length=200)
    sfx = models.CharField(max_length=200)
    frame_type = None
    border_style = None
    def __str__(self):
        return f"Description: {self.description}, mood: {self.mood}"
    

gen/forms.py
from django import forms


class WebtoonForm(forms.Form):
    location = forms.CharField(max_length=20)
    details = forms.CharField(max_length=200)
    character1name = forms.CharField(max_length=20)
    character1details = forms.CharField(max_length=200)
    character2name = forms.CharField(max_length=20)
    character2details = forms.CharField(max_length=200)

accounts/views.py
from django.shortcuts import render

# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

gen/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from gen.forms import WebtoonForm
from gen.image import generate_image
from gen.models import *
from gen.segmentation import *
from django.contrib.auth.models import User

from gen.ai import get_ai_generated_story

# TODO

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator

def home(request):
    context = {}
    return render(request, "gen/home.html", context)


# take user input for characters and context, then generate story
# user form POST endpoint
def input(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        print("received POST request")
        # create a form instance and populate it with data from the request:
        form = WebtoonForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # Using the data from form.cleaned_data:
            # TODO: see if we want to add other fields like genre
            location = form.cleaned_data['location']
            details = form.cleaned_data['details']
            character1name = form.cleaned_data['character1name']
            character1details = form.cleaned_data['character1details']
            character2name = form.cleaned_data['character2name']
            character2details = form.cleaned_data['character2details']

            # save the user's characters and context in the database
            user = request.user
            user.save()
            context = Context(location = location, user = user, details = details)
            character1 = Character(user = user, name = character1name, details = character1details)
            character2 = Character(user = user, name = character2name, details = character2details)
            context.save()
            character1.save()
            character2.save()

            # call text gen API
            ai_story = get_ai_generated_story(location, details, character1name, character1details,
                                                   character2name, character2details)
            story = Story(user = user , text = ai_story, title = f"{character1name} and {character2name}'s story")

            # save generated story to database
            story.save()
            # redirect to show story
            return render(request, "gen/story.html", {'story': ai_story})
        else:
            print(f"FORM ERRORS: {form.errors}")
            print("form was not valid...")
    # if a GET (or any other method) we'll create a blank form
    else:
        form = WebtoonForm()
    return render(request, "gen/input.html", {"form": form})

# display story
def story(request):
    stories = Story.objects.filter(user = request.user)
    context = {}
    if len(stories) > 0:
        context['story'] = stories[len(stories)-1].text
    return render(request, "gen/story.html", context)

def segments(request):
    stories = Story.objects.filter(user = request.user)
    context = {}
    story = None
    if len(stories) > 0:
        story = stories[len(stories)-1]
    if story:
        segments = create_segments(story.text)
        for text in segments:
            segment = Segment(text = text, story = story)
            segment.save()
        story.num_panels = len(segments)
        story.save()
        context = {'segments': segments, 'num_segments': len(segments)}
    return render(request, "gen/segments.html", context)

def images(request):
    stories = Story.objects.filter(user = request.user)
    context = {}
    story = None
    if len(stories) > 0:
        story = stories[len(stories)-1]
    if story:
        segments = Segment.objects.filter(story = story)
        for segment in segments[:5]: # DALL-E Free Tier max 5 queries / min
            
            if segment.image == '':
                print(f"Generating image for text:{segment.text}")
                # generate image if we haven't yet
                segment.image = generate_image(segment.text) # populate URL
                # print(f"Saved image URL as {segment.image}")
                segment.save()
        story.num_panels = len(segments)
        story.save()
        context = {'segments':segments, 'num_panels': story.num_panels}
    return render(request, "gen/images.html", context)

def webtoon(request):
    context = {}
    return render(request, "gen/webtoon.html", context)

gen/templates/gen/home.html
{% load static %}

<link rel="stylesheet" href="{% static 'gen/style.css' %}">
<p>User homepage</p>
<a href="{% url 'gen:input'%}">Create your webtoon</a>

gen/templates/gen/images.html
{% load static %}

<link rel="stylesheet" href="{% static 'gen/style.css' %}">
<p>View the images created here</p>
{% for segment in segments %}

    <p><img src="{{ segment.image }}"></p>
    
{% endfor %}

<a href="{% url 'gen:webtoon' %}">See the final webtoon!</a>

gen/templates/gen/input.html
{% load static %}

<link rel="stylesheet" href="{% static 'gen/style.css' %}">
<p>Create characters here</p>
{% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <label for="location">Location: </label>
    <input id="location" type="text" name="location" value="{{ current_location}}">
    <br>
    <label for="details">Details </label>
    <input id="details" type="text" name="details" value="{{ current_details }}">
    <br>
    <label for="character1name">character 1 name: </label>
    <input id="character1name" type="text" name="character1name" value="">
    <br>
    <label for="character1details">Details: </label>
    <input id="character1details" type="text" name="character1details" value="">
    <br>
    <label for="character2name">character 2 name: </label>
    <input id="character2name" type="text" name="character2name" value="">
    <br>
    <label for="character2details">Details: </label>
    <input id="character2details" type="text" name="character2details" value="">
    <br>
    <input type="submit" value="OK">
</form>

gen/templates/gen/segments.html
{% load static %}

<link rel="stylesheet" href="{% static 'gen/style.css' %}">
<p>View the story segments here</p>
<h1> There are {{ num_segments }} segments</h1>
{% for segment in segments %}

    <li>{{segment}}</li>
    
{% endfor %}
<a href="{% url 'gen:images'%}">View segment images!</a>

gen/templates/gen/story.html
{% load static %}

<link rel="stylesheet" href="{% static 'gen/style.css' %}">
<p>View the story created here</p>
<p>Story: {{story}}</p> 
<a href="{% url 'gen:segments'%}">View story segments!</a>

gen/templates/gen/webtoon.html
{% load static %}

<link rel="stylesheet" href="{% static 'gen/style.css' %}">
<p>View the created webtoon here</p>

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}WEBTOONZ~{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <a href="/gen/">Make some webtoons</a>


  <form id="logout-form" method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">Log out</button>
  </form>
  <p><a href="{% url 'password_reset' %}">Reset Password</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="/admin/">Admin Log In</a>
  <a href="{% url 'signup' %}">Sign up</a>

{% endif %}
{% endblock %}